package Models;

public enum MenuOption {
    VIEW_RECENT_TRANSACTIONS,
    ENTER_NEW_TRANSACTION,
    EDIT_TRANSACTIONS,
    DELETE_TRANSACTIONS,
    VIEW_CATEGORIES,
    ADD_CATEGORY,
    ENTER_BUDGET,
    VIEW_REMAINING_BUDGET,
    TRACK_PROGRESS,
    EXIT
}
